import 'models/project.dart';

class PortfolioData {
  static final List<Project> projects = [
    Project(
      id: '1',
      title: 'Trendify - E-Commerce App',
      description: 'Modern E-Commerce application built with Flutter & Dart, featuring clean UI, product browsing, product details, cart functionality, and smooth shopping experience.',
      imageUrl: 'https://picsum.photos/seed/trendify/400/300',
      githubUrl: 'https://github.com/afahitech/trendify',
      liveUrl: 'https://github.com/afahitech/trendify',
      technologies: ['Flutter', 'Dart', 'Firebase', 'UI Design'],
      date: DateTime(2024, 1, 1),
      isFeatured: true,
    ),
    Project(
      id: '2',
      title: 'Task Manager App',
      description: 'Productivity app to manage daily tasks with simple and clean Flutter UI.',
      imageUrl: 'https://picsum.photos/seed/taskmanager/400/300',
      githubUrl: 'https://github.com/afahitech/taskmanager',
      liveUrl: 'https://github.com/afahitech/taskmanager',
      technologies: ['Flutter', 'Dart', 'UI Design'],
      date: DateTime(2024, 2, 1),
      isFeatured: true,
    ),
    Project(
      id: '3',
      title: 'Contact Management App',
      description: 'Flutter based contact management application with clean UI and local database CRUD functionality.',
      imageUrl: 'https://picsum.photos/seed/contactapp/400/300',
      githubUrl: 'https://github.com/afahitech/contactapp',
      liveUrl: 'https://github.com/afahitech/contactapp',
      technologies: ['Flutter', 'Dart', 'SQLite', 'CRUD'],
      date: DateTime(2024, 3, 1),
    ),
    Project(
      id: '4',
      title: 'BMI Calculator',
      description: 'Flutter based BMI calculator application with clean and user-friendly interface.',
      imageUrl: 'https://picsum.photos/seed/bmi/400/300',
      githubUrl: 'https://github.com/afahitech/bmi',
      liveUrl: 'https://github.com/afahitech/bmi',
      technologies: ['Flutter', 'Java', 'UI Design'],
      date: DateTime(2024, 4, 1),
    ),
    Project(
      id: '5',
      title: 'Weather App',
      description: 'Weather application using API integration to show real-time weather information.',
      imageUrl: 'https://picsum.photos/seed/weather/400/300',
      githubUrl: 'https://github.com/afahitech/weather',
      liveUrl: 'https://github.com/afahitech/weather',
      technologies: ['Flutter', 'API', 'Dart'],
      date: DateTime(2024, 5, 1),
    ),
    Project(
      id: '6',
      title: 'Quote Vault',
      description: 'Motivational quote application built with Flutter and local storage.',
      imageUrl: 'https://picsum.photos/seed/quote/400/300',
      githubUrl: 'https://github.com/afahitech/quotevault',
      liveUrl: 'https://github.com/afahitech/quotevault',
      technologies: ['Flutter', 'Provider', 'Local Storage'],
      date: DateTime(2024, 6, 1),
    ),
    Project(
      id: '7',
      title: 'Flashcard Quiz App',
      description: 'Interactive quiz application developed during CodeAlpha internship.',
      imageUrl: 'https://picsum.photos/seed/flashcard/400/300',
      githubUrl: 'https://github.com/afahitech/flashcard',
      liveUrl: 'https://github.com/afahitech/flashcard',
      technologies: ['Flutter', 'Dart', 'CodeAlpha'],
      date: DateTime(2024, 7, 1),
    ),
    Project(
      id: '8',
      title: 'Scientific Calculator',
      description: 'Modern calculator application with advanced mathematical operations.',
      imageUrl: 'https://picsum.photos/seed/calculator/400/300',
      githubUrl: 'https://github.com/afahitech/calculator',
      liveUrl: 'https://github.com/afahitech/calculator',
      technologies: ['Flutter', 'Dart'],
      date: DateTime(2024, 8, 1),
    ),
    Project(
      id: '9',
      title: 'Flutter Finance App',
      description: 'A banking app with real-time transaction tracking',
      imageUrl: 'https://picsum.photos/seed/finance/400/300',
      githubUrl: 'https://github.com/afahitech/finance_app',
      liveUrl: 'https://finance-app-demo.vercel.app',
      technologies: ['Flutter', 'BLoC', 'Hive', 'Charts'],
      date: DateTime(2024, 8, 28),
      isFeatured: true,
    ),
  ];
}